/// Flutter icons ThinIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ThinIcons
///      fonts:
///       - asset: fonts/ThinIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class ThinIcons {
  ThinIcons._();

  static const _kFontFam = 'ThinIcons';

  static const IconData heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData right_open_big = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData diamond = const IconData(0xe845, fontFamily: _kFontFam);
}
